### ISSUE TITLE
ShiftJIS bug, doesn't work.

### ISSUE THREAD

**Issue by JackOfBadTrades** [TesterTesterov/mscScriptTool#2]
Doesn't work with Evolimit - Package edition.
It manages to disassemble the script just fine, but it can assemble it back.
 Console output:
```
- Длина файла:
81098
- Границы сегментов:
[491, 378, 99]
- Техсекция один:
[5, 74433]
[1, 74447]
[2, 74461]
[6, 74527]
[3, 74541]
[4, 74555]
[34, 74621]
[35, 74765]
[36, 75076]
[37, 75156]
[38, 75207]
[39, 75274]
[40, 75377]
[41, 75594]
[42, 75715]
[22, 75800]
[23, 75922]
[24, 75976]
[25, 76073]
[26, 76134]
[27, 76237]
[28, 76298]
[29, 76359]
[30, 76402]
[31, 76490]
[32, 76551]
[33, 76665]
[7, 76719]
[8, 76734]
[9, 76749]
[10, 76764]
[11, 76779]
[12, 76794]
[13, 76809]
[14, 76824]
[15, 76839]
[16, 76854]
[17, 76869]
[18, 76884]
[19, 76899]
[20, 76914]
[21, 76929]
- Техсекция два:
[1, 76944]
[2, 77126]
[3, 77168]
[4, 78127]
[5, 78127]
[6, 78306]
[7, 78638]
[8, 78846]
[9, 79670]
[10, 79746]
[11, 79925]
'shift_jis' codec can't decode byte 0x87 in position 7762: illegal multibyte sequence
```
[Script file + decrypted script file.
](https://files.catbox.moe/byyuod.zip)
Also:
![main_UpGmQlOeo0](https://user-images.githubusercontent.com/80150464/236078555-5675d9b0-ffb7-4648-826b-da7c68af8a89.jpg)
Perhaps you wrote the English UI for the silky tool and copypasted it? Simple fix though.

**Comment by TesterTesterov** [comment]
I'll look into the problem now.

**Comment by TesterTesterov** [comment]
@JackOfBadTrades, done. Try [this release](https://github.com/TesterTesterov/mscScriptTool/releases/tag/1.1). Use the new default (cp932), though.

**Comment by JackOfBadTrades** [comment]
Success! Thank you very much!
![EVOLIMIT_OG15hN1FtD](https://user-images.githubusercontent.com/80150464/236740382-7c7a2850-992c-4aa4-ba0e-172ff57d395f.jpg)
...
On another note, what is `\u3000` ? It appears at the beginning of some strings. It seems to be some sort of special character, but the engine fails to render it when your tool reassembles the script.
![EVOLIMIT_KAaJZs7lim](https://user-images.githubusercontent.com/80150464/236741291-27002205-26fd-4f9d-8c99-9f676429e12b.jpg)

**Comment by TesterTesterov** [comment]
@JackOfBadTrades, ah, this would be the big (full-width) spacing characters. This is the tool fault; the newer tools of mine does not have this problem. Though, in order to fix it, I would need to change the arguments writing/reading system itself, so I'll do it if you *really* need this kind of fix. Otherwise, you can just change \u3000 to the big Japanese spacing symbol in the disassembled (.txt) file. The script will display it correctly.

**Comment by JackOfBadTrades** [comment]
Ah ok then. Was just testing the tool. Won't be needing it any time soon.
Again, thanks for fixing it.
